package.json

took out prepare from package.json

---

.vscode/settings.json
public/style.css
server/db/models/index.js
server/db/models/product.js
server/db/models/review.js
server/db/models/user.js

adding bootstrap and basic models

---

server/db/models/user.js

editing user model

---

client/components/Grass.js
client/components/GrassList.js
client/components/navbar.js
client/components/user-home.js
client/history.js
client/store/index.js

some components

---

client/components/Checkout.js
client/components/SingleGrass.js
client/components/UserForm.js
client/components/navbar.js

adding some new components

---

client/app.js
client/components/Cart.js
client/components/Grass.js
client/components/GrassList.js
client/components/UserForm.js
client/components/navbar.js
client/components/user-home.js
client/history.js
client/store/index.js
server/api/users.js
server/index.js

made navbar

---

client/components/GrassList.js
client/routes.js

now you can run npm start and get a dummy homepage

---

client/components/ProductCard.js
client/components/ProductList.js
package-lock.json
package.json
public/index.html
public/style.css

Implemented all products view on home page with Semantic UI

---

client/components/AuthForm.js
client/components/index.js
client/routes.js
client/store/user.js
package-lock.json
script/seed.js
server/api/users.js

ali and I's new signup form

---

client/components/Cart.js
client/components/Home.js
client/components/ProductCard.js
client/components/ProductList.js
client/components/SingleProduct.js
client/store/cart.js
client/store/index.js
package-lock.json
script/seed.js
server/api/cart.js
server/api/index.js
server/api/users.js
server/db/models/cart.js
server/db/models/index.js

Started work on making a cart vertical slice

---

client/components/navbar.js

gave a message when a user logs in

---

script/seed.js

Extended seed file to contain more types of grass

---

server/db/db.js

minor issues

---

client/components/Checkout.js
client/components/Stripe.js
client/routes.js
package-lock.json
package.json
public/index.html
server/api/cart.js
server/api/users.spec.1.js

Stripe is mostly implemented, once the cart is done, then the proper amount will be sen

---

client/components/AuthForm.js
client/components/Cart.js
client/components/LogIn.js
client/components/ProductCard.js
client/components/navbar.js
client/store/user.js
package-lock.json
script/seed.js

Made the appearance of login match that of signup

---

client/components/LogIn.js

fixed minor issues on logging in

---

client/components/Checkout.js
client/components/SingleProduct.js
client/components/Stripe.js
client/components/index.js
client/routes.js
client/store/cart.js
server/api/cart.js
server/api/products.js
server/api/users.js
server/api/users.spec.js
server/db/models/index.js

Just tidied things up a little bit as I was reviewing this morning

---

client/components/Cart.js
client/components/Checkout.js
client/components/LogIn.js
client/store/cart.js
client/store/user.js
server/api/cart.js
server/api/users.js

added totals to both checkout and cart

---

client/components/Cart.js
client/components/LogIn.js
client/components/navbar.js
client/store/cart.js
server/api/users.js

finished saved cart, login - load cart, logout - empty cart

---

client/components/Checkout.js
client/components/Stripe.js
client/components/UserForm.js
server/api/cart.js
server/api/users.js
server/db/models/promo.js

Checkoutform can satisfy a purchase and reset the cart
